// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/bean/PlayerItemBean.proto

package com.bean.game.proto;

public final class PlayerItemBeanMsg {
  private PlayerItemBeanMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerItemBeanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *主键
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *主键
     * </pre>
     */
    int getId();

    // optional int32 baseItemId = 2;
    /**
     * <code>optional int32 baseItemId = 2;</code>
     *
     * <pre>
     *基础道具id
     * </pre>
     */
    boolean hasBaseItemId();
    /**
     * <code>optional int32 baseItemId = 2;</code>
     *
     * <pre>
     *基础道具id
     * </pre>
     */
    int getBaseItemId();

    // optional int32 num = 3;
    /**
     * <code>optional int32 num = 3;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    boolean hasNum();
    /**
     * <code>optional int32 num = 3;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    int getNum();

    // optional int32 type = 4;
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    int getType();

    // optional string node = 5;
    /**
     * <code>optional string node = 5;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasNode();
    /**
     * <code>optional string node = 5;</code>
     *
     * <pre>
     * </pre>
     */
    java.lang.String getNode();
    /**
     * <code>optional string node = 5;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getNodeBytes();

    // optional string test1 = 6;
    /**
     * <code>optional string test1 = 6;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasTest1();
    /**
     * <code>optional string test1 = 6;</code>
     *
     * <pre>
     * </pre>
     */
    java.lang.String getTest1();
    /**
     * <code>optional string test1 = 6;</code>
     *
     * <pre>
     * </pre>
     */
    com.google.protobuf.ByteString
        getTest1Bytes();
  }
  /**
   * Protobuf type {@code com.proto.message.PlayerItemBean}
   */
  public static final class PlayerItemBean extends
      com.google.protobuf.GeneratedMessage
      implements PlayerItemBeanOrBuilder {
    // Use PlayerItemBean.newBuilder() to construct.
    private PlayerItemBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerItemBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerItemBean defaultInstance;
    public static PlayerItemBean getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerItemBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerItemBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              baseItemId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              num_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              node_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              test1_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bean.game.proto.PlayerItemBeanMsg.internal_static_com_proto_message_PlayerItemBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bean.game.proto.PlayerItemBeanMsg.internal_static_com_proto_message_PlayerItemBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean.class, com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerItemBean> PARSER =
        new com.google.protobuf.AbstractParser<PlayerItemBean>() {
      public PlayerItemBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerItemBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerItemBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *主键
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     *
     * <pre>
     *主键
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // optional int32 baseItemId = 2;
    public static final int BASEITEMID_FIELD_NUMBER = 2;
    private int baseItemId_;
    /**
     * <code>optional int32 baseItemId = 2;</code>
     *
     * <pre>
     *基础道具id
     * </pre>
     */
    public boolean hasBaseItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 baseItemId = 2;</code>
     *
     * <pre>
     *基础道具id
     * </pre>
     */
    public int getBaseItemId() {
      return baseItemId_;
    }

    // optional int32 num = 3;
    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    /**
     * <code>optional int32 num = 3;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 num = 3;</code>
     *
     * <pre>
     *数量
     * </pre>
     */
    public int getNum() {
      return num_;
    }

    // optional int32 type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 type = 4;</code>
     *
     * <pre>
     *道具类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // optional string node = 5;
    public static final int NODE_FIELD_NUMBER = 5;
    private java.lang.Object node_;
    /**
     * <code>optional string node = 5;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasNode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string node = 5;</code>
     *
     * <pre>
     * </pre>
     */
    public java.lang.String getNode() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          node_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string node = 5;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNodeBytes() {
      java.lang.Object ref = node_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string test1 = 6;
    public static final int TEST1_FIELD_NUMBER = 6;
    private java.lang.Object test1_;
    /**
     * <code>optional string test1 = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasTest1() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string test1 = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public java.lang.String getTest1() {
      java.lang.Object ref = test1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          test1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string test1 = 6;</code>
     *
     * <pre>
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTest1Bytes() {
      java.lang.Object ref = test1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      baseItemId_ = 0;
      num_ = 0;
      type_ = 0;
      node_ = "";
      test1_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, baseItemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, num_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNodeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTest1Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, baseItemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, num_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNodeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTest1Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.proto.message.PlayerItemBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bean.game.proto.PlayerItemBeanMsg.internal_static_com_proto_message_PlayerItemBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bean.game.proto.PlayerItemBeanMsg.internal_static_com_proto_message_PlayerItemBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean.class, com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean.Builder.class);
      }

      // Construct using com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        baseItemId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        node_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        test1_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bean.game.proto.PlayerItemBeanMsg.internal_static_com_proto_message_PlayerItemBean_descriptor;
      }

      public com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean getDefaultInstanceForType() {
        return com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean.getDefaultInstance();
      }

      public com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean build() {
        com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean buildPartial() {
        com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean result = new com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.baseItemId_ = baseItemId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.num_ = num_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.node_ = node_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.test1_ = test1_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean) {
          return mergeFrom((com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean other) {
        if (other == com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasBaseItemId()) {
          setBaseItemId(other.getBaseItemId());
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasNode()) {
          bitField0_ |= 0x00000010;
          node_ = other.node_;
          onChanged();
        }
        if (other.hasTest1()) {
          bitField0_ |= 0x00000020;
          test1_ = other.test1_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bean.game.proto.PlayerItemBeanMsg.PlayerItemBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *主键
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *主键
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *主键
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       *
       * <pre>
       *主键
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional int32 baseItemId = 2;
      private int baseItemId_ ;
      /**
       * <code>optional int32 baseItemId = 2;</code>
       *
       * <pre>
       *基础道具id
       * </pre>
       */
      public boolean hasBaseItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 baseItemId = 2;</code>
       *
       * <pre>
       *基础道具id
       * </pre>
       */
      public int getBaseItemId() {
        return baseItemId_;
      }
      /**
       * <code>optional int32 baseItemId = 2;</code>
       *
       * <pre>
       *基础道具id
       * </pre>
       */
      public Builder setBaseItemId(int value) {
        bitField0_ |= 0x00000002;
        baseItemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 baseItemId = 2;</code>
       *
       * <pre>
       *基础道具id
       * </pre>
       */
      public Builder clearBaseItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        baseItemId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 num = 3;
      private int num_ ;
      /**
       * <code>optional int32 num = 3;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 num = 3;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>optional int32 num = 3;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000004;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 num = 3;</code>
       *
       * <pre>
       *数量
       * </pre>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        num_ = 0;
        onChanged();
        return this;
      }

      // optional int32 type = 4;
      private int type_ ;
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 4;</code>
       *
       * <pre>
       *道具类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional string node = 5;
      private java.lang.Object node_ = "";
      /**
       * <code>optional string node = 5;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasNode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string node = 5;</code>
       *
       * <pre>
       * </pre>
       */
      public java.lang.String getNode() {
        java.lang.Object ref = node_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          node_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string node = 5;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNodeBytes() {
        java.lang.Object ref = node_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          node_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string node = 5;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setNode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        node_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string node = 5;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearNode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        node_ = getDefaultInstance().getNode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string node = 5;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setNodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        node_ = value;
        onChanged();
        return this;
      }

      // optional string test1 = 6;
      private java.lang.Object test1_ = "";
      /**
       * <code>optional string test1 = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasTest1() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string test1 = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public java.lang.String getTest1() {
        java.lang.Object ref = test1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          test1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string test1 = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTest1Bytes() {
        java.lang.Object ref = test1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string test1 = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setTest1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        test1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string test1 = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearTest1() {
        bitField0_ = (bitField0_ & ~0x00000020);
        test1_ = getDefaultInstance().getTest1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string test1 = 6;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setTest1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        test1_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.proto.message.PlayerItemBean)
    }

    static {
      defaultInstance = new PlayerItemBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.proto.message.PlayerItemBean)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_proto_message_PlayerItemBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_proto_message_PlayerItemBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037proto/bean/PlayerItemBean.proto\022\021com.p" +
      "roto.message\"h\n\016PlayerItemBean\022\n\n\002id\030\001 \001" +
      "(\005\022\022\n\nbaseItemId\030\002 \001(\005\022\013\n\003num\030\003 \001(\005\022\014\n\004t" +
      "ype\030\004 \001(\005\022\014\n\004node\030\005 \001(\t\022\r\n\005test1\030\006 \001(\tB(" +
      "\n\023com.bean.game.protoB\021PlayerItemBeanMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_proto_message_PlayerItemBean_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_proto_message_PlayerItemBean_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_proto_message_PlayerItemBean_descriptor,
              new java.lang.String[] { "Id", "BaseItemId", "Num", "Type", "Node", "Test1", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
